### ISSUE TITLE
Implement line search modifiers based on the strong Wolfe conditions && implement backtracking method

### ISSUE THREAD

**Issue by donRumata03** [spanish-inquisition-optimization/GradientDescent#5]
Line searches would also accept terminate conditions: they are still functions and could be based on `eps`, `iterations`, `Wolfe conditions`

**Comment by Vovkaez** [comment]
Видимо условия Вольфе не получится применить к произвольному линейному спуску (не понятно что делать, если полученная alpha не подходит). Как я понял, backtracking это облегченный метод, который учитывает только первое условие про sufficient decrease. Сделал отдельный поиск, выполняющий оба условия #13
